Repository probot/probot, pull requests merged in 2023-11, with the labels that each got.

#1821 feat: Migrate to modern dependencies for v13
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/apps/default.ts
  src/apps/setup.ts
  src/bin/probot-receive.ts
  src/bin/probot.ts
  src/bin/read-cli-options.ts
  src/context.ts
  src/helpers/alias-log.ts
  src/helpers/get-log.ts
  src/helpers/resolve-app-function.ts
  src/manifest-creation.ts
  src/octokit/get-authenticated-octokit.ts
  src/octokit/get-octokit-throttle-options.ts
  src/octokit/get-probot-octokit-with-defaults.ts
  src/octokit/get-webhooks.ts
  src/octokit/octokit-plugin-probot-request-logging.ts
  src/probot.ts
  src/server/logging-middleware.ts
  src/server/server.ts
  src/types.ts
  src/views/import.ts
  src/views/probot.ts
  src/views/setup.ts
  src/views/success.ts
  test/__snapshots__/probot.test.ts.snap
  test/apps/__snapshots__/default.test.ts.snap
  test/apps/__snapshots__/setup.test.ts.snap
  test/apps/default.test.ts
  test/apps/setup.test.ts
  test/bin/is-supported-node-version.test.ts
  test/context.test.ts
  test/create-node-middleware.test.ts
  test/create-probot.test.ts
  test/deprecations.test.ts
  test/e2e/e2e.test.ts
  test/e2e/hello-world.js
  test/fixtures/plugin/stub-plugin.ts
  test/helpers/capture-log-output.ts
  test/helpers/is-production.test.ts
  test/helpers/load-package-json.test.ts
  test/manifest-creation.test.ts
  test/probot-octokit.test.ts
  test/probot.test.ts
  test/resolver.test.ts
  test/run.test.ts
  test/server.test.ts
  test/server/logging-middleware.test.ts
  test/webhook-proxy.test.ts
  tsconfig.json
  vitest.config.ts
Labels: released on @beta

#1916 chore: code cleanup
  src/octokit/get-authenticated-octokit.ts
  src/octokit/get-webhooks.ts
Labels: maintenance

#1924 fix: derive `Server` log from `Probot` log
  src/server/server.ts
Labels: bug

#1925 ci(workflow): fix `test` workflow to assure it is not skipped if dependant jobs fails
  .github/workflows/test.yml
Labels: maintenance

#1927 build(lockfile): update `@octokit/oauth-methods` to 4.0.1
  package-lock.json
Labels: maintenance

#1929 chore: add comment to `SimplifiedObject`
  src/types.ts
Labels: maintenance
